/**
 * オフライン会場マップ - データ管理モジュール (VENUE_DATA)
 * 最新編集データ (全諸室・ACP統合保存版)
 */

const VENUE_DATA = {
  "floors": [
    {
      "id": "outdoor",
      "name": "屋外",
      "nameEn": "Outdoor Site Plan",
      "mapBg": "assets/outdoor.png"
    },
    {
      "id": "1f",
      "name": "1階",
      "nameEn": "1st Floor (Pools & Field Operations)",
      "mapBg": "assets/floor1.png"
    },
    {
      "id": "2f",
      "name": "2階",
      "nameEn": "2nd Floor (VIP, Press & Commentary)",
      "mapBg": "assets/floor2.png"
    }
  ],
  "departments": [
    {
      "code": "ALL",
      "name": "全部署 (All Departments)"
    },
    {
      "code": "SPT",
      "name": "競技・スポーツ (Sports)",
      "color": "#007aff"
    },
    {
      "code": "OFS",
      "name": "大会要人・プロトコル (Official / Protocol)",
      "color": "#af52de"
    },
    {
      "code": "TEC",
      "name": "計測・テクノロジー (Technology & OVR)",
      "color": "#00c7be"
    },
    {
      "code": "SEC",
      "name": "警備・セキュリティ (Security / VSCC)",
      "color": "#ff3b30"
    },
    {
      "code": "SPP",
      "name": "演出・プロダクション (Special Production)",
      "color": "#ff9500"
    },
    {
      "code": "CER",
      "name": "表彰・セレモニー (Ceremonies)",
      "color": "#ff2d55"
    },
    {
      "code": "BRS",
      "name": "放送・中継 (Broadcast / HB)",
      "color": "#5856d6"
    },
    {
      "code": "PRS",
      "name": "報道・プレス (Press & Media)",
      "color": "#ff9500"
    },
    {
      "code": "DOP",
      "name": "ドーピング検査 (Doping Control)",
      "color": "#34c759"
    },
    {
      "code": "PEM",
      "name": "アクレディ・ID (Check-In)",
      "color": "#ff2d55"
    },
    {
      "code": "VEM",
      "name": "ボランティア (Volunteer & VOC)",
      "color": "#34c759"
    },
    {
      "code": "CNW",
      "name": "清掃・廃棄物 (Cleaning & Waste)",
      "color": "#8e8e93"
    },
    {
      "code": "LOG",
      "name": "資材・物流 (Logistics)",
      "color": "#5856d6"
    },
    {
      "code": "TRA",
      "name": "輸送・駐車場 (Transport)",
      "color": "#007aff"
    },
    {
      "code": "VNI",
      "name": "会場インフラ (Infrastructure)",
      "color": "#64748b"
    },
    {
      "code": "BIL",
      "name": "二国間・運営 (Bilateral)",
      "color": "#64748b"
    },
    {
      "code": "EVS",
      "name": "観客・案内サービス (Event Services)",
      "color": "#ff9500"
    },
    {
      "code": "FNB",
      "name": "飲食・ケータリング (Food & Beverage)",
      "color": "#ff9500"
    },
    {
      "code": "MED",
      "name": "救護・医務 (Medical)",
      "color": "#34c759"
    },
    {
      "code": "NRG",
      "name": "電力・エネルギー (Energy / Power)",
      "color": "#ffcc00"
    },
    {
      "code": "GLE",
      "name": "敷地管理 (Green & Landscape)",
      "color": "#34c759"
    },
    {
      "code": "TKT",
      "name": "チケット (Ticketing)",
      "color": "#ff2d55"
    }
  ],
  "zones": [],
  "rooms": [
    {
      "id": "RM-SPT-001",
      "code": "SPT-1",
      "name": "Sport Information",
      "nameEn": "SPT 1 - Sport Information",
      "dept": "SPT",
      "floor": "1f",
      "x": 25.4,
      "y": 56.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.1,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-002",
      "code": "SPT-9",
      "name": "Athlete Training Area (Warm Up Pool)",
      "nameEn": "SPT 9 - Athlete Training Area (Warm Up Pool)",
      "dept": "SPT",
      "floor": "1f",
      "x": 81.7,
      "y": 36.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: BLUE | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-003",
      "code": "SPT-10",
      "name": "FOP Equipment Storage",
      "nameEn": "SPT 10 - FOP Equipment Storage",
      "dept": "SPT",
      "floor": "1f",
      "x": 80.8,
      "y": 56.2,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: RED | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-004",
      "code": "SPT-11",
      "name": "Sport Equipment Storage",
      "nameEn": "SPT 11 - Sport Equipment Storage",
      "dept": "SPT",
      "floor": "1f",
      "x": 80,
      "y": 58.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-005",
      "code": "SPT-14",
      "name": "Athlete Change Room (Men)",
      "nameEn": "SPT 14 - Athlete Change Room (Men)",
      "dept": "SPT",
      "floor": "1f",
      "x": 38.3,
      "y": 64.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-006",
      "code": "SPT-15",
      "name": "Athlete Change Room (Women)",
      "nameEn": "SPT 15 - Athlete Change Room (Women)",
      "dept": "SPT",
      "floor": "1f",
      "x": 33.3,
      "y": 62.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-007",
      "code": "SPT-17",
      "name": "Athlete Lounge",
      "nameEn": "SPT 17 - Athlete Lounge",
      "dept": "SPT",
      "floor": "1f",
      "x": 68.1,
      "y": 62.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 8.2,
      "h": 5.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-008",
      "code": "SPT-18",
      "name": "Athlete Dining",
      "nameEn": "SPT 18 - Athlete Dining",
      "dept": "SPT",
      "floor": "1f",
      "x": 17.5,
      "y": 64.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 4.2,
      "h": 22.2,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-009",
      "code": "SPT-23",
      "name": "Call Room",
      "nameEn": "SPT 23 - Call Room",
      "dept": "SPT",
      "floor": "1f",
      "x": 67.3,
      "y": 56.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 7.3,
      "h": 4.3,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-010",
      "code": "SPT-59",
      "name": "Technical Officials Meeting Room",
      "nameEn": "SPT 59 - Technical Officials Meeting Room",
      "dept": "SPT",
      "floor": "1f",
      "x": 76.6,
      "y": 15.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.1,
      "h": 5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-011",
      "code": "SPT-64",
      "name": "Video Judge Room",
      "nameEn": "SPT 64 - Video Judge Room",
      "dept": "SPT",
      "floor": "1f",
      "x": 71,
      "y": 17.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2,
      "h": 4.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-012",
      "code": "SPT-66",
      "name": "Kiss&Cry",
      "nameEn": "SPT 66 - Kiss&Cry",
      "dept": "SPT",
      "floor": "1f",
      "x": 69.6,
      "y": 28.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-013",
      "code": "SPT-67",
      "name": "Free Swimming Area",
      "nameEn": "SPT 67 - Free Swimming Area",
      "dept": "SPT",
      "floor": "1f",
      "x": 70,
      "y": 72.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 9,
      "h": 9.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-014",
      "code": "SPT-68",
      "name": "Dry Land Training Stretch Area",
      "nameEn": "SPT 68 - Dry Land Training Stretch Area",
      "dept": "SPT",
      "floor": "1f",
      "x": 59.2,
      "y": 75,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.8,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-015",
      "code": "SPT-69",
      "name": "Hair Setting Space",
      "nameEn": "SPT 69 - Hair Setting Space",
      "dept": "SPT",
      "floor": "1f",
      "x": 32.2,
      "y": 58.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.9,
      "h": 3,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-016",
      "code": "SPT-83",
      "name": "Preparation Area",
      "nameEn": "SPT 83 - Preparation Area",
      "dept": "SPT",
      "floor": "1f",
      "x": 71,
      "y": 15.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 1.9,
      "h": 4.3,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-017",
      "code": "SPT-90",
      "name": "Pray Room for Athletes",
      "nameEn": "SPT 90 - Pray Room for Athletes",
      "dept": "SPT",
      "floor": "1f",
      "x": 60.7,
      "y": 82.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-018",
      "code": "SPT-101",
      "name": "Competition Management",
      "nameEn": "SPT 101 - Competition Management",
      "dept": "SPT",
      "floor": "1f",
      "x": 73,
      "y": 14.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 1.5,
      "h": 5.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-019",
      "code": "SPT-106",
      "name": "Staff Toilets-Men Urinal",
      "nameEn": "SPT 106 - Staff Toilets-Men Urinal",
      "dept": "SPT",
      "floor": "1f",
      "x": 37.2,
      "y": 58.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-020",
      "code": "SPT-107",
      "name": "Staff Toilets-Men",
      "nameEn": "SPT 107 - Staff Toilets-Men",
      "dept": "SPT",
      "floor": "1f",
      "x": 40.5,
      "y": 60.9,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.1,
      "h": 2.2,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-021",
      "code": "SPT-108",
      "name": "Staff Toilets-Women",
      "nameEn": "SPT 108 - Staff Toilets-Women",
      "dept": "SPT",
      "floor": "1f",
      "x": 32.7,
      "y": 71,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.5,
      "h": 4,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-022",
      "code": "SPT-109",
      "name": "Staff Toilets-Accessible",
      "nameEn": "SPT 109 - Staff Toilets-Accessible",
      "dept": "SPT",
      "floor": "1f",
      "x": 35.5,
      "y": 59.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))"
    },
    {
      "id": "RM-SPT-023",
      "code": "SPT-201",
      "name": "IF Office",
      "nameEn": "SPT 201 - IF Office",
      "dept": "SPT",
      "floor": "1f",
      "x": 55,
      "y": 15.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.4,
      "h": 5.4,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-024",
      "code": "SPT-203+227",
      "name": "IF/AF President Office",
      "nameEn": "SPT 203+227 - IF/AF President Office",
      "dept": "SPT",
      "floor": "1f",
      "x": 51.5,
      "y": 7.2,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.1,
      "h": 4.9,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-025",
      "code": "SPT-205",
      "name": "TD Office",
      "nameEn": "SPT 205 - TD Office",
      "dept": "SPT",
      "floor": "1f",
      "x": 74.8,
      "y": 14.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 1.9,
      "h": 4.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-026",
      "code": "SPT-508",
      "name": "Team Leaders Meeting Room",
      "nameEn": "SPT 508 - Team Leaders Meeting Room",
      "dept": "SPT",
      "floor": "1f",
      "x": 78.1,
      "y": 16.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2,
      "h": 5.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-027",
      "code": "SPT-509",
      "name": "Judges/TC Platform 1",
      "nameEn": "SPT 509 - Judges/TC Platform 1",
      "dept": "SPT",
      "floor": "1f",
      "x": 65.1,
      "y": 15.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.4,
      "h": 4.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-028",
      "code": "SPT-509",
      "name": "Judges/TC Platform 2",
      "nameEn": "SPT 509 - Judges/TC Platform 2",
      "dept": "SPT",
      "floor": "1f",
      "x": 67.7,
      "y": 15.2,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.3,
      "h": 4.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPT-029",
      "code": "SPT-513",
      "name": "Music Operations Room",
      "nameEn": "SPT 513 - Music Operations Room",
      "dept": "SPT",
      "floor": "1f",
      "x": 61.5,
      "y": 15.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 2.5,
      "h": 5.2,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-030",
      "code": "OFS-1",
      "name": "Staff Office",
      "nameEn": "OFS 1 - Staff Office",
      "dept": "OFS",
      "floor": "1f",
      "x": 50.3,
      "y": 9.6,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 1.9,
      "h": 5.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-031",
      "code": "OFS-2",
      "name": "Protocol Office",
      "nameEn": "OFS 2 - Protocol Office",
      "dept": "OFS",
      "floor": "1f",
      "x": 51.1,
      "y": 9.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-OFS-2",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 2.6,
      "h": 7,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-032",
      "code": "OFS-3",
      "name": "OCA Family Lounge",
      "nameEn": "OFS 3 - OCA Family Lounge",
      "dept": "OFS",
      "floor": "1f",
      "x": 57.3,
      "y": 8.2,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-033",
      "code": "OFS-6",
      "name": "Flag Area for Ceremonies",
      "nameEn": "OFS 6 - Flag Area for Ceremonies",
      "dept": "OFS",
      "floor": "1f",
      "x": 37.2,
      "y": 27.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 2.3,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-034",
      "code": "OFS-7",
      "name": "Urinal Toilet (Men)",
      "nameEn": "OFS 7 - Urinal Toilet (Men)",
      "dept": "OFS",
      "floor": "1f",
      "x": 61.4,
      "y": 2.2,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-035",
      "code": "OFS-8",
      "name": "Cubicle Toilet (Men)",
      "nameEn": "OFS 8 - Cubicle Toilet (Men)",
      "dept": "OFS",
      "floor": "1f",
      "x": 50.3,
      "y": 2.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-036",
      "code": "OFS-9",
      "name": "Cubicle Toilet (Women)",
      "nameEn": "OFS 9 - Cubicle Toilet (Women)",
      "dept": "OFS",
      "floor": "1f",
      "x": 54.3,
      "y": 2.2,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-037",
      "code": "OFS-10",
      "name": "Accessible Toilet",
      "nameEn": "OFS 10 - Accessible Toilet",
      "dept": "OFS",
      "floor": "1f",
      "x": 58,
      "y": 2.2,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-038",
      "code": "TEC-1",
      "name": "T&S",
      "nameEn": "TEC 1 - T&S",
      "dept": "TEC",
      "floor": "1f",
      "x": 97.7,
      "y": 56.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-1",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 2.7,
      "h": 3.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-039",
      "code": "TEC-2",
      "name": "OVR",
      "nameEn": "TEC 2 - OVR",
      "dept": "TEC",
      "floor": "outdoor",
      "x": 96.3,
      "y": 59.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-2",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-040",
      "code": "TEC-3",
      "name": "Storage for T&S",
      "nameEn": "TEC 3 - Storage for T&S",
      "dept": "TEC",
      "floor": "outdoor",
      "x": 48.4,
      "y": 15,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-3",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-041",
      "code": "TEC-4",
      "name": "TER",
      "nameEn": "TEC 4 - TER",
      "dept": "TEC",
      "floor": "1f",
      "x": 47.1,
      "y": 9.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-4",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 4.5,
      "h": 1.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-042",
      "code": "TEC-6",
      "name": "Cross Connect Frame",
      "nameEn": "TEC 6 - Cross Connect Frame",
      "dept": "TEC",
      "floor": "1f",
      "x": 49,
      "y": 15.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-6",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 2.9,
      "h": 5.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-043",
      "code": "TEC-7",
      "name": "VTO",
      "nameEn": "TEC 7 - VTO",
      "dept": "TEC",
      "floor": "1f",
      "x": 97.8,
      "y": 61.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-7",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))"
    },
    {
      "id": "RM-TEC-044",
      "code": "TEC-10",
      "name": "Radio Distribution Room",
      "nameEn": "TEC 10 - Radio Distribution Room",
      "dept": "TEC",
      "floor": "outdoor",
      "x": 34.6,
      "y": 35,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-10",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TEC-045",
      "code": "TEC-11",
      "name": "Screen",
      "nameEn": "TEC 11 - Screen",
      "dept": "TEC",
      "floor": "1f",
      "x": 42.3,
      "y": 20.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-TEC-11",
      "desc": "Zone: RED | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 1.9,
      "h": 3.4,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-046",
      "code": "SEC-1",
      "name": "VSCC",
      "nameEn": "SEC 1 - VSCC",
      "dept": "SEC",
      "floor": "1f",
      "x": 42.1,
      "y": 9.9,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-1",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-047",
      "code": "SEC-2",
      "name": "Fire Command Centre",
      "nameEn": "SEC 2 - Fire Command Centre",
      "dept": "SEC",
      "floor": "1f",
      "x": 41.2,
      "y": 8.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-2",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-048",
      "code": "SEC-5",
      "name": "Police Break & Dining Area",
      "nameEn": "SEC 5 - Police Break & Dining Area",
      "dept": "SEC",
      "floor": "1f",
      "x": 22,
      "y": 71.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-5",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 2.3,
      "h": 3,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPP-049",
      "code": "SPP-1",
      "name": "SPP Control Area",
      "nameEn": "SPP 1 - SPP Control Area",
      "dept": "SPP",
      "floor": "1f",
      "x": 60.1,
      "y": 16,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SPP-1",
      "desc": "Zone: RED | Department: SPP (演出・プロダクション (Special Production))",
      "w": 2.3,
      "h": 5.4,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPP-050",
      "code": "SPP-2",
      "name": "SPP Work Room",
      "nameEn": "SPP 2 - SPP Work Room",
      "dept": "SPP",
      "floor": "1f",
      "x": 58.8,
      "y": 15.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SPP-2",
      "desc": "Zone: RED | Department: SPP (演出・プロダクション (Special Production))",
      "w": 2.1,
      "h": 5.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPP-051",
      "code": "SPP-3",
      "name": "SPP Storage",
      "nameEn": "SPP 3 - SPP Storage",
      "dept": "SPP",
      "floor": "1f",
      "x": 46.2,
      "y": 15.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SPP-3",
      "desc": "Zone: RED | Department: SPP (演出・プロダクション (Special Production))",
      "w": 2.1,
      "h": 4.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-SPP-052",
      "code": "SPP-4",
      "name": "Performer Waiting Room",
      "nameEn": "SPP 4 - Performer Waiting Room",
      "dept": "SPP",
      "floor": "1f",
      "x": 57.9,
      "y": 16,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SPP-4",
      "desc": "Zone: RED | Department: SPP (演出・プロダクション (Special Production))",
      "w": 1.9,
      "h": 4.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-CER-053",
      "code": "CER-1",
      "name": "Waiting Room",
      "nameEn": "CER 1 - Waiting Room",
      "dept": "CER",
      "floor": "1f",
      "x": 29.6,
      "y": 49.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-CER-1",
      "desc": "Zone: 2 | Department: CER (表彰・セレモニー (Ceremonies))"
    },
    {
      "id": "RM-CER-054",
      "code": "CER-2",
      "name": "Preparation Room",
      "nameEn": "CER 2 - Preparation Room",
      "dept": "CER",
      "floor": "1f",
      "x": 30.8,
      "y": 42.9,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-CER-2",
      "desc": "Zone: 5 | Department: CER (表彰・セレモニー (Ceremonies))",
      "w": 3,
      "h": 2.3,
      "pdfUrl": ""
    },
    {
      "id": "RM-CER-055",
      "code": "CER-3",
      "name": "Storage for Ceremonies",
      "nameEn": "CER 3 - Storage for Ceremonies",
      "dept": "CER",
      "floor": "1f",
      "x": 58.3,
      "y": 9.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-CER-3",
      "desc": "Zone: RED | Department: CER (表彰・セレモニー (Ceremonies))",
      "w": 1.8,
      "h": 1.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-CER-056",
      "code": "CER-4",
      "name": "Changing Room",
      "nameEn": "CER 4 - Changing Room",
      "dept": "CER",
      "floor": "1f",
      "x": 30.2,
      "y": 41.9,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: CER (表彰・セレモニー (Ceremonies))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-057",
      "code": "BRS-15",
      "name": "Staff Office",
      "nameEn": "BRS 15 - Staff Office",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 83.2,
      "y": 14.8,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: BRS (放送・中継 (Broadcast / HB))"
    },
    {
      "id": "RM-BRS-058",
      "code": "BRS-19",
      "name": "Broadcast Mixed Zone",
      "nameEn": "BRS 19 - Broadcast Mixed Zone",
      "dept": "BRS",
      "floor": "1f",
      "x": 77.8,
      "y": 49.2,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-19",
      "desc": "Zone: 4,5+SACDS | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 6.8,
      "h": 3.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-059",
      "code": "BRS-20",
      "name": "HB Camera Platform",
      "nameEn": "BRS 20 - HB Camera Platform",
      "dept": "BRS",
      "floor": "2f",
      "x": 61.4,
      "y": 50.4,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-060",
      "code": "BRS-20",
      "name": "HB Camera Platform (footprint)",
      "nameEn": "BRS 20 - HB Camera Platform (footprint)",
      "dept": "BRS",
      "floor": "2f",
      "x": 41.2,
      "y": 21.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-061",
      "code": "BRS-20",
      "name": "HB Camera Platform",
      "nameEn": "BRS 20 - HB Camera Platform",
      "dept": "BRS",
      "floor": "2f",
      "x": 61.9,
      "y": 21.4,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-062",
      "code": "PRS-3",
      "name": "Mixed Zone",
      "nameEn": "PRS 3 - Mixed Zone",
      "dept": "PRS",
      "floor": "1f",
      "x": 85.1,
      "y": 49.1,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-3",
      "desc": "Zone: 4,5+SACDS | Department: PRS (報道・プレス (Press & Media))",
      "w": 7.3,
      "h": 3.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-063",
      "code": "PRS-4",
      "name": "Photographer Position",
      "nameEn": "PRS 4 - Photographer Position",
      "dept": "PRS",
      "floor": "2f",
      "x": 61.9,
      "y": 54.5,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-4",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-DOP-064",
      "code": "DOP-1",
      "name": "Doping Control Station",
      "nameEn": "DOP 1 - Doping Control Station",
      "dept": "DOP",
      "floor": "1f",
      "x": 47.3,
      "y": 59.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-DOP-1",
      "desc": "Zone: 2+SACDs | Department: DOP (ドーピング検査 (Doping Control))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PEM-065",
      "code": "PEM-1",
      "name": "Check-In & Help Desk (Check In Centre)",
      "nameEn": "PEM 1 - Check-In & Help Desk (Check In Centre)",
      "dept": "PEM",
      "floor": "1f",
      "x": 25.8,
      "y": 40.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: PEM (アクレディテーション・ID (Check-In / ID))",
      "w": 2.3,
      "h": 3.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-VEM-066",
      "code": "VEM-1",
      "name": "VOC",
      "nameEn": "VEM 1 - VOC",
      "dept": "VEM",
      "floor": "1f",
      "x": 30.5,
      "y": 52.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: VEM (ボランティア (Volunteer & VOC))",
      "w": 3.9,
      "h": 5,
      "pdfUrl": ""
    },
    {
      "id": "RM-CNW-067",
      "code": "CNW-1",
      "name": "Staff Office",
      "nameEn": "CNW 1 - Staff Office",
      "dept": "CNW",
      "floor": "1f",
      "x": 29.4,
      "y": 41.7,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: CNW (清掃・廃棄物 (Cleaning & Waste))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-CNW-068",
      "code": "CNW-2",
      "name": "Contractor Office",
      "nameEn": "CNW 2 - Contractor Office",
      "dept": "CNW",
      "floor": "1f",
      "x": 24.2,
      "y": 51.7,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: CNW (清掃・廃棄物 (Cleaning & Waste))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-LOG-069",
      "code": "LOG-1",
      "name": "Staff Office",
      "nameEn": "LOG 1 - Staff Office",
      "dept": "LOG",
      "floor": "1f",
      "x": 31.1,
      "y": 46.6,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: LOG (資材・物流 (Logistics))",
      "w": 2.3,
      "h": 4.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-LOG-070",
      "code": "LOG-2",
      "name": "Contractor Office",
      "nameEn": "LOG 2 - Contractor Office",
      "dept": "LOG",
      "floor": "1f",
      "x": 31.3,
      "y": 48.7,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: LOG (資材・物流 (Logistics))",
      "w": 2.2,
      "h": 4.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-TRA-071",
      "code": "TRA-1",
      "name": "Staff Office",
      "nameEn": "TRA 1 - Staff Office",
      "dept": "TRA",
      "floor": "1f",
      "x": 32.9,
      "y": 45.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: TRA (輸送・駐車場 (Transport))",
      "w": 2.3,
      "h": 4.2,
      "pdfUrl": ""
    },
    {
      "id": "RM-TRA-072",
      "code": "TRA-2",
      "name": "Contractor Office",
      "nameEn": "TRA 2 - Contractor Office",
      "dept": "TRA",
      "floor": "1f",
      "x": 30.6,
      "y": 43.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: TRA (輸送・駐車場 (Transport))",
      "w": 2.1,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-VNI-073",
      "code": "VNI-1",
      "name": "Staff Office",
      "nameEn": "VNI 1 - Staff Office",
      "dept": "VNI",
      "floor": "1f",
      "x": 32.5,
      "y": 43.9,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: VNI (会場インフラ (Venue Infrastructure))",
      "w": 3.2,
      "h": 2.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-VNI-074",
      "code": "VNI-2",
      "name": "Contractor Office",
      "nameEn": "VNI 2 - Contractor Office",
      "dept": "VNI",
      "floor": "1f",
      "x": 29.7,
      "y": 47.5,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: VNI (会場インフラ (Venue Infrastructure))",
      "w": 2,
      "h": 4,
      "pdfUrl": ""
    },
    {
      "id": "RM-BIL-075",
      "code": "BIL-2",
      "name": "Contractor Office",
      "nameEn": "BIL 2 - Contractor Office",
      "dept": "BIL",
      "floor": "1f",
      "x": 32.1,
      "y": 40.5,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: BIL (二国間・運営 (Bilateral))",
      "w": 3.4,
      "h": 2.4,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-076",
      "code": "EVS-2",
      "name": "Public Information Booth",
      "nameEn": "EVS 2 - Public Information Booth",
      "dept": "EVS",
      "floor": "2f",
      "x": 26.5,
      "y": 42.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-077",
      "code": "EVS-3",
      "name": "Multi Faith Room",
      "nameEn": "EVS 3 - Multi Faith Room",
      "dept": "EVS",
      "floor": "2f",
      "x": 25.5,
      "y": 30.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 2.5,
      "h": 3.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-078",
      "code": "EVS-4",
      "name": "Accessible Nursery & Baby Change Room",
      "nameEn": "EVS 4 - Accessible Nursery & Baby Change Room",
      "dept": "EVS",
      "floor": "2f",
      "x": 26.3,
      "y": 25.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 4,
      "h": 4.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-079",
      "code": "EVS-5",
      "name": "Wheelchair Storage Area",
      "nameEn": "EVS 5 - Wheelchair Storage Area",
      "dept": "EVS",
      "floor": "2f",
      "x": 37.1,
      "y": 61.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-080",
      "code": "EVS-6",
      "name": "Stroller Storage Area",
      "nameEn": "EVS 6 - Stroller Storage Area",
      "dept": "EVS",
      "floor": "1f",
      "x": 31.8,
      "y": 18.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 2.4,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-081",
      "code": "EVS-7",
      "name": "Assistant Dog Toilet",
      "nameEn": "EVS 7 - Assistant Dog Toilet",
      "dept": "EVS",
      "floor": "2f",
      "x": 16,
      "y": 39.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 2.8,
      "h": 4.7,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-082",
      "code": "EVS-9",
      "name": "Spectator Seating",
      "nameEn": "EVS 9 - Spectator Seating",
      "dept": "EVS",
      "floor": "2f",
      "x": 45.6,
      "y": 15.4,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 16.4,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-083",
      "code": "EVS-10",
      "name": "Accessible Seating",
      "nameEn": "EVS 10 - Accessible Seating",
      "dept": "EVS",
      "floor": "2f",
      "x": 38.4,
      "y": 10.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 7.5,
      "h": 8.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-084",
      "code": "EVS-11",
      "name": "Calm Down/Cool Down Room",
      "nameEn": "EVS 11 - Calm Down/Cool Down Room",
      "dept": "EVS",
      "floor": "2f",
      "x": 25.8,
      "y": 34.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 3.5,
      "h": 2.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-085",
      "code": "EVS-12",
      "name": "Urinal Toilet (Men)",
      "nameEn": "EVS 12 - Urinal Toilet (Men)",
      "dept": "EVS",
      "floor": "2f",
      "x": 33,
      "y": 22.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 4.3,
      "h": 4.1,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-086",
      "code": "EVS-13",
      "name": "Cubicle Toilet (Men)",
      "nameEn": "EVS 13 - Cubicle Toilet (Men)",
      "dept": "EVS",
      "floor": "2f",
      "x": 33.1,
      "y": 28.2,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-087",
      "code": "EVS-14",
      "name": "Cubicle Toilet (Women)",
      "nameEn": "EVS 14 - Cubicle Toilet (Women)",
      "dept": "EVS",
      "floor": "2f",
      "x": 32.3,
      "y": 37.2,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-088",
      "code": "EVS-15",
      "name": "Accessible Toilet",
      "nameEn": "EVS 15 - Accessible Toilet",
      "dept": "EVS",
      "floor": "2f",
      "x": 32.6,
      "y": 33.1,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-089",
      "code": "PRS-1",
      "name": "Sub Press Center",
      "nameEn": "PRS 1 - Sub Press Center",
      "dept": "PRS",
      "floor": "2f",
      "x": 25.2,
      "y": 73.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-1",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-090",
      "code": "PRS-2",
      "name": "Press Conference Room",
      "nameEn": "PRS 2 - Press Conference Room",
      "dept": "PRS",
      "floor": "2f",
      "x": 31.4,
      "y": 76.7,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-2",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5.8,
      "h": 5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-091",
      "code": "PRS-4",
      "name": "Photographer Position",
      "nameEn": "PRS 4 - Photographer Position",
      "dept": "PRS",
      "floor": "2f",
      "x": 61.5,
      "y": 61.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-4",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-092",
      "code": "PRS-5",
      "name": "Press Tribune-No Table",
      "nameEn": "PRS 5 - Press Tribune-No Table",
      "dept": "PRS",
      "floor": "2f",
      "x": 67.7,
      "y": 15.4,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-093",
      "code": "PRS-6",
      "name": "Press Tribune-With Table",
      "nameEn": "PRS 6 - Press Tribune-With Table",
      "dept": "PRS",
      "floor": "2f",
      "x": 71.6,
      "y": 12.5,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-6",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-094",
      "code": "PRS-7",
      "name": "Press Tribune-With Table-Accessible",
      "nameEn": "PRS 7 - Press Tribune-With Table-Accessible",
      "dept": "PRS",
      "floor": "2f",
      "x": 67.2,
      "y": 12.5,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-PRS-095",
      "code": "PRS-8",
      "name": "Press Operation Office",
      "nameEn": "PRS 8 - Press Operation Office",
      "dept": "PRS",
      "floor": "2f",
      "x": 20.8,
      "y": 76.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-PRS-8",
      "desc": "Zone: 4 | Department: PRS (報道・プレス (Press & Media))"
    },
    {
      "id": "RM-BRS-096",
      "code": "BRS-17",
      "name": "RHB Commentary Position",
      "nameEn": "BRS 17 - RHB Commentary Position",
      "dept": "BRS",
      "floor": "2f",
      "x": 56.8,
      "y": 12.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-17",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-097",
      "code": "BRS-20",
      "name": "HB Camera Platform",
      "nameEn": "BRS 20 - HB Camera Platform",
      "dept": "BRS",
      "floor": "2f",
      "x": 52.3,
      "y": 13,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-098",
      "code": "OFS-4",
      "name": "OCA Family Seating",
      "nameEn": "OFS 4 - OCA Family Seating",
      "dept": "OFS",
      "floor": "2f",
      "x": 62.1,
      "y": 14.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-OFS-4",
      "desc": "Zone: 6 | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 7,
      "h": 5.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-099",
      "code": "BRS-23",
      "name": "Observer Seats",
      "nameEn": "BRS 23 - Observer Seats",
      "dept": "BRS",
      "floor": "2f",
      "x": 71.5,
      "y": 15.5,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-23",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))"
    },
    {
      "id": "RM-BRS-100",
      "code": "BRS-24",
      "name": "Presentation Studio",
      "nameEn": "BRS 24 - Presentation Studio",
      "dept": "BRS",
      "floor": "2f",
      "x": 47.8,
      "y": 9,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-24",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 14.7,
      "h": 4.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-101",
      "code": "BRS-25",
      "name": "Urinal Toilet (Men)",
      "nameEn": "BRS 25 - Urinal Toilet (Men)",
      "dept": "BRS",
      "floor": "2f",
      "x": 87.9,
      "y": 7.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-102",
      "code": "BRS-26",
      "name": "Cubicle Toilet (Men)",
      "nameEn": "BRS 26 - Cubicle Toilet (Men)",
      "dept": "BRS",
      "floor": "2f",
      "x": 84.9,
      "y": 3.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-103",
      "code": "BRS-27",
      "name": "Cubicle Toilet (Women)",
      "nameEn": "BRS 27 - Cubicle Toilet (Women)",
      "dept": "BRS",
      "floor": "2f",
      "x": 85.9,
      "y": 7.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-104",
      "code": "BRS-28",
      "name": "Accessible Toilet",
      "nameEn": "BRS 28 - Accessible Toilet",
      "dept": "BRS",
      "floor": "2f",
      "x": 82.2,
      "y": 7.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-FNB-105",
      "code": "FNB-1",
      "name": "Concessions/Points of Sale (POS)",
      "nameEn": "FNB 1 - Concessions/Points of Sale (POS)",
      "dept": "FNB",
      "floor": "outdoor",
      "x": 46.5,
      "y": 16.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: FNB (飲食・ケータリング (Food & Beverage))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-MED-106",
      "code": "MED-3",
      "name": "Aid Station",
      "nameEn": "MED 3 - Aid Station",
      "dept": "MED",
      "floor": "2f",
      "x": 26.6,
      "y": 48.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: MED (救護・医務 (Medical))",
      "w": 4,
      "h": 5.3,
      "pdfUrl": ""
    },
    {
      "id": "RM-VEM-107",
      "code": "VEM-2",
      "name": "Workforce Break & Dining Area",
      "nameEn": "VEM 2 - Workforce Break & Dining Area",
      "dept": "VEM",
      "floor": "2f",
      "x": 49,
      "y": 66,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: VEM (ボランティア (Volunteer & VOC))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-108",
      "code": "SEC-4",
      "name": "Fire Break & Dining Area",
      "nameEn": "SEC 4 - Fire Break & Dining Area",
      "dept": "SEC",
      "floor": "1f",
      "x": 42.4,
      "y": 5.8,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TRA-109",
      "code": "TRA-3",
      "name": "Driver's Waiting Room (In Secure)",
      "nameEn": "TRA 3 - Driver's Waiting Room (In Secure)",
      "dept": "TRA",
      "floor": "1f",
      "x": 16.8,
      "y": 15.5,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: RED | Department: TRA (輸送・駐車場 (Transport))"
    },
    {
      "id": "RM-SPT-110",
      "code": "SPT-2",
      "name": "Athlete Seating (SDA)",
      "nameEn": "SPT 2 - Athlete Seating (SDA)",
      "dept": "SPT",
      "floor": "2f",
      "x": 67.2,
      "y": 56.9,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SPT-2",
      "desc": "Zone: 2 | Department: SPT (競技・スポーツ (Sports))",
      "w": 3.8,
      "h": 6.4,
      "pdfUrl": ""
    },
    {
      "id": "RM-CNW-111",
      "code": "CNW-3",
      "name": "Waste Storage Area",
      "nameEn": "CNW 3 - Waste Storage Area",
      "dept": "CNW",
      "floor": "outdoor",
      "x": 41.3,
      "y": 39,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: CNW (清掃・廃棄物 (Cleaning & Waste))"
    },
    {
      "id": "RM-CNW-112",
      "code": "CNW-4",
      "name": "Waste Sorting Area",
      "nameEn": "CNW 4 - Waste Sorting Area",
      "dept": "CNW",
      "floor": "outdoor",
      "x": 41.1,
      "y": 36.1,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: CNW (清掃・廃棄物 (Cleaning & Waste))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-113",
      "code": "SEC-3",
      "name": "Police Command Centre",
      "nameEn": "SEC 3 - Police Command Centre",
      "dept": "SEC",
      "floor": "1f",
      "x": 22.4,
      "y": 67.9,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-3",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 3.1,
      "h": 1.8,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-114",
      "code": "SEC-6",
      "name": "Vehicle Screening Area (VSA)",
      "nameEn": "SEC 6 - Vehicle Screening Area (VSA)",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 22.3,
      "y": 24.8,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-115",
      "code": "SEC-7",
      "name": "Vehicle Screening Area (VSA)",
      "nameEn": "SEC 7 - Vehicle Screening Area (VSA)",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 20.8,
      "y": 27.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-116",
      "code": "SEC-8",
      "name": "Pedestrian Screening Area - Accredited (PSA)",
      "nameEn": "SEC 8 - Pedestrian Screening Area - Accredited (PSA)",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 32.2,
      "y": 59.6,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-8",
      "desc": "Zone: FOH | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-117",
      "code": "SEC-9",
      "name": "Pedestrian Screening Area - Spectators (PSA)",
      "nameEn": "SEC 9 - Pedestrian Screening Area - Spectators (PSA)",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 32,
      "y": 63.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "ACP-SEC-9",
      "desc": "Zone: FOH | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-118",
      "code": "SEC-11",
      "name": "Police Parking",
      "nameEn": "SEC 11 - Police Parking",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 42.5,
      "y": 23.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-119",
      "code": "SEC-12",
      "name": "Self-Defense Forces Command Centre",
      "nameEn": "SEC 12 - Self-Defense Forces Command Centre",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 36.6,
      "y": 22.9,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-SEC-120",
      "code": "SEC-13",
      "name": "Self-Defense Forces Command Parking",
      "nameEn": "SEC 13 - Self-Defense Forces Command Parking",
      "dept": "SEC",
      "floor": "outdoor",
      "x": 34.1,
      "y": 20.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: RED | Department: SEC (警備・セキュリティ (Security))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-121",
      "code": "BRS-1",
      "name": "HB Office",
      "nameEn": "BRS 1 - HB Office",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 75,
      "y": 15.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-1",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-122",
      "code": "BRS-2",
      "name": "RHB Office",
      "nameEn": "BRS 2 - RHB Office",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 82,
      "y": 11.5,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-2",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-123",
      "code": "BRS-3",
      "name": "HB Dining",
      "nameEn": "BRS 3 - HB Dining",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 80.7,
      "y": 15.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-3",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-124",
      "code": "BRS-4",
      "name": "RHB Dining",
      "nameEn": "BRS 4 - RHB Dining",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 77.6,
      "y": 13.3,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-4",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-125",
      "code": "BRS-5",
      "name": "HB Production Room",
      "nameEn": "BRS 5 - HB Production Room",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 91.2,
      "y": 15.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-5",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-126",
      "code": "BRS-7",
      "name": "HB Audio",
      "nameEn": "BRS 7 - HB Audio",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 71.5,
      "y": 14.6,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-7",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-127",
      "code": "BRS-9",
      "name": "HB CER (Centralized Equipment Room)",
      "nameEn": "BRS 9 - HB CER (Centralized Equipment Room)",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 73.3,
      "y": 12.7,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-9",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-128",
      "code": "BRS-11",
      "name": "TOC (Technical Operation Centre)",
      "nameEn": "BRS 11 - TOC (Technical Operation Centre)",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 79,
      "y": 21,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-11",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-129",
      "code": "BRS-13",
      "name": "HB Equipment Storage",
      "nameEn": "BRS 13 - HB Equipment Storage",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 90.6,
      "y": 13.8,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-13",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-BRS-130",
      "code": "BRS-14",
      "name": "RHB Equipment Storage",
      "nameEn": "BRS 14 - RHB Equipment Storage",
      "dept": "BRS",
      "floor": "outdoor",
      "x": 86.2,
      "y": 15.1,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "ACP-BRS-14",
      "desc": "Zone: 5 | Department: BRS (放送・中継 (Broadcast / HB))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-NRG-131",
      "code": "NRG-1",
      "name": "Staff Office",
      "nameEn": "NRG 1 - Staff Office",
      "dept": "NRG",
      "floor": "outdoor",
      "x": 96.1,
      "y": 71.3,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: NRG (電力・エネルギー (Energy / Power))"
    },
    {
      "id": "RM-NRG-132",
      "code": "NRG-2",
      "name": "Storage",
      "nameEn": "NRG 2 - Storage",
      "dept": "NRG",
      "floor": "outdoor",
      "x": 96.3,
      "y": 62.9,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: NRG (電力・エネルギー (Energy / Power))"
    },
    {
      "id": "RM-NRG-133",
      "code": "NRG-3",
      "name": "Overlay Power Area",
      "nameEn": "NRG 3 - Overlay Power Area",
      "dept": "NRG",
      "floor": "outdoor",
      "x": 96.4,
      "y": 79.8,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: NRG (電力・エネルギー (Energy / Power))"
    },
    {
      "id": "RM-NRG-134",
      "code": "NRG-4",
      "name": "Break Area",
      "nameEn": "NRG 4 - Break Area",
      "dept": "NRG",
      "floor": "outdoor",
      "x": 96,
      "y": 67.9,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: NRG (電力・エネルギー (Energy / Power))"
    },
    {
      "id": "RM-GLE-135",
      "code": "GLE-1",
      "name": "Site Office",
      "nameEn": "GLE 1 - Site Office",
      "dept": "GLE",
      "floor": "outdoor",
      "x": 40.2,
      "y": 14.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: GLE (敷地管理 (Green & Landscape))"
    },
    {
      "id": "RM-GLE-136",
      "code": "GLE-2",
      "name": "Break Area",
      "nameEn": "GLE 2 - Break Area",
      "dept": "GLE",
      "floor": "1f",
      "x": 30.9,
      "y": 44.7,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: GLE (敷地管理 (Green & Landscape))",
      "w": 2.1,
      "h": 3.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-GLE-137",
      "code": "GLE-3",
      "name": "Storage",
      "nameEn": "GLE 3 - Storage",
      "dept": "GLE",
      "floor": "outdoor",
      "x": 27.8,
      "y": 25.1,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: GLE (敷地管理 (Green & Landscape))"
    },
    {
      "id": "RM-FNB-138",
      "code": "FNB-3",
      "name": "Kitchen Car Area (For Staff)",
      "nameEn": "FNB 3 - Kitchen Car Area (For Staff)",
      "dept": "FNB",
      "floor": "outdoor",
      "x": 45.7,
      "y": 13.6,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: FNB (飲食・ケータリング (Food & Beverage))"
    },
    {
      "id": "RM-FNB-139",
      "code": "FNB-10",
      "name": "Freezing & Cold Temperature Storage",
      "nameEn": "FNB 10 - Freezing & Cold Temperature Storage",
      "dept": "FNB",
      "floor": "outdoor",
      "x": 31.5,
      "y": 27.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: FNB (飲食・ケータリング (Food & Beverage))"
    },
    {
      "id": "RM-FNB-140",
      "code": "FNB-11",
      "name": "Normal Temperature Storage",
      "nameEn": "FNB 11 - Normal Temperature Storage",
      "dept": "FNB",
      "floor": "outdoor",
      "x": 32.9,
      "y": 30.1,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: FNB (飲食・ケータリング (Food & Beverage))"
    },
    {
      "id": "RM-TRA-141",
      "code": "TRA-4",
      "name": "Parking (In Secure)",
      "nameEn": "TRA 4 - Parking (In Secure)",
      "dept": "TRA",
      "floor": "outdoor",
      "x": 28.3,
      "y": 30.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: TRA (輸送・駐車場 (Transport))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-TRA-142",
      "code": "TRA-5",
      "name": "Parking (Non Secure)",
      "nameEn": "TRA 5 - Parking (Non Secure)",
      "dept": "TRA",
      "floor": "outdoor",
      "x": 21.9,
      "y": 45.6,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: TRA (輸送・駐車場 (Transport))",
      "w": 7.4,
      "h": 6,
      "pdfUrl": ""
    },
    {
      "id": "RM-LOG-143",
      "code": "LOG-3",
      "name": "Compound",
      "nameEn": "LOG 3 - Compound",
      "dept": "LOG",
      "floor": "outdoor",
      "x": 96.3,
      "y": 75.8,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: LOG (資材・物流 (Logistics))"
    },
    {
      "id": "RM-TKT-144",
      "code": "TKT-1",
      "name": "Ticket Box Office (TBO)",
      "nameEn": "TKT 1 - Ticket Box Office (TBO)",
      "dept": "TKT",
      "floor": "outdoor",
      "x": 16.4,
      "y": 61.4,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: TKT (チケット (Ticketing))"
    },
    {
      "id": "RM-TKT-145",
      "code": "TKT-2",
      "name": "Ticket Resolution Office (TRO)",
      "nameEn": "TKT 2 - Ticket Resolution Office (TRO)",
      "dept": "TKT",
      "floor": "outdoor",
      "x": 19.2,
      "y": 59.3,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: TKT (チケット (Ticketing))"
    },
    {
      "id": "RM-TKT-146",
      "code": "TKT-3",
      "name": "Ticket Team Office (TTO)",
      "nameEn": "TKT 3 - Ticket Team Office (TTO)",
      "dept": "TKT",
      "floor": "outdoor",
      "x": 16.4,
      "y": 57.6,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: TKT (チケット (Ticketing))"
    },
    {
      "id": "RM-TEC-147",
      "code": "TEC-5",
      "name": "Storage",
      "nameEn": "TEC 5 - Storage",
      "dept": "TEC",
      "floor": "outdoor",
      "x": 34.1,
      "y": 29.8,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: TEC (計測・テクノロジー (Technology & OVR))"
    },
    {
      "id": "RM-TEC-148",
      "code": "TEC-12",
      "name": "Parking for Radio Monitoring Vehicle",
      "nameEn": "TEC 12 - Parking for Radio Monitoring Vehicle",
      "dept": "TEC",
      "floor": "outdoor",
      "x": 35.5,
      "y": 27,
      "zoneId": "ZONE_OUTDOOR_MAIN",
      "acp": "なし",
      "desc": "Zone: WHITE | Department: TEC (計測・テクノロジー (Technology & OVR))"
    },
    {
      "id": "RM-TEC-149",
      "code": "TEC-13",
      "name": "Spectrum Desk",
      "nameEn": "TEC 13 - Spectrum Desk",
      "dept": "TEC",
      "floor": "1f",
      "x": 80.6,
      "y": 10.7,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: TEC (計測・テクノロジー (Technology & OVR))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-EVS-150",
      "code": "EVS-8",
      "name": "Queueing Area",
      "nameEn": "EVS 8 - Queueing Area",
      "dept": "EVS",
      "floor": "outdoor",
      "x": 26.7,
      "y": 65.3,
      "zoneId": "ZONE_1F_MAIN",
      "acp": "なし",
      "desc": "Zone: FOH | Department: EVS (観客・案内サービス (Event Services))",
      "w": 5,
      "h": 3.5,
      "pdfUrl": ""
    },
    {
      "id": "RM-OFS-151",
      "code": "OFS-5",
      "name": "Flag Area for Participants",
      "nameEn": "OFS 5 - Flag Area for Participants",
      "dept": "OFS",
      "floor": "1f",
      "x": 37.2,
      "y": 24,
      "zoneId": "ZONE_2F_MAIN",
      "acp": "なし",
      "desc": "Zone: BLUE | Department: OFS (大会要人・プロトコル (Official / Protocol))",
      "w": 2.7,
      "h": 3.6,
      "pdfUrl": ""
    },
    {
      "id": "RM-USER-1789603854661",
      "code": "test",
      "name": "test",
      "nameEn": "test",
      "dept": "SPT",
      "floor": "outdoor",
      "x": 51.8,
      "y": 21.9,
      "acp": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "RM-USER-1789627861092",
      "code": "sec",
      "name": "SEC03",
      "nameEn": "sec",
      "dept": "SPT",
      "floor": "1f",
      "x": 36.2,
      "y": 8.5,
      "acp": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": "",
      "w": 3.4,
      "h": 5.3
    },
    {
      "id": "RM-USER-5025",
      "name": "スイミミル",
      "code": "FNB",
      "nameEn": "",
      "dept": "FNB",
      "floor": "1f",
      "x": 37.4,
      "y": 15.5,
      "w": 4.7,
      "h": 3,
      "acp": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": "AthleteDiningのキッチンスタッフ控室・更衣室"
    }
  ],
  "acps": [
    {
      "id": "ACP-CER-3",
      "code": "ACP-CER-3",
      "name": "関所: Storage for Ceremonies (CER-3)",
      "floor": "1f",
      "x": 61.4,
      "y": 10.6,
      "passLevel": "Level CER (認証関係者パス)",
      "desc": "Zone RED へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-USER-1789627921156",
      "code": "TEC04 TER",
      "name": "TEC04 TER",
      "floor": "1f",
      "x": 41.2,
      "y": 10.9,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628078203",
      "code": "TEC TER",
      "name": "TEC TER",
      "floor": "1f",
      "x": 44.1,
      "y": 11.1,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628097060",
      "code": "TEC TER",
      "name": "TEC TER",
      "floor": "1f",
      "x": 46.9,
      "y": 11.2,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628133211",
      "code": "OFS Protocol Office",
      "name": "OFS Protocol Office",
      "floor": "1f",
      "x": 49.8,
      "y": 10.8,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628179779",
      "code": "OFS",
      "name": "OFS 07～10",
      "floor": "1f",
      "x": 54.1,
      "y": 10.4,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628200211",
      "code": "OFS 貴賓室　階段",
      "name": "OFS 貴賓室　階段",
      "floor": "1f",
      "x": 59.7,
      "y": 10.6,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628295966",
      "code": "SPT Video judge Room",
      "name": "SPT Video judge Room",
      "floor": "1f",
      "x": 70.6,
      "y": 14.2,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628227459",
      "code": "SPT",
      "name": "SPT meeting room",
      "floor": "1f",
      "x": 73.5,
      "y": 13,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628384910",
      "code": "SPＴ",
      "name": "FOP境界（北）",
      "floor": "1f",
      "x": 69.6,
      "y": 17.9,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628342724",
      "code": "SPT　meetingroom",
      "name": "SPT　meetingroom",
      "floor": "1f",
      "x": 75.8,
      "y": 17.7,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628418043",
      "code": "SPT",
      "name": "SPT 　competition management office",
      "floor": "1f",
      "x": 66.3,
      "y": 13.1,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628487091",
      "code": "SPT",
      "name": "SPT competition　management　office",
      "floor": "1f",
      "x": 66.2,
      "y": 17.8,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628534470",
      "code": "SPP",
      "name": "SPP01～04",
      "floor": "1f",
      "x": 62.2,
      "y": 12.9,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628555127",
      "code": "SPP",
      "name": "SPP01～04",
      "floor": "1f",
      "x": 63.3,
      "y": 17.8,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-SPP-2",
      "code": "SPP",
      "name": "SPP 音響",
      "floor": "1f",
      "x": 57.9,
      "y": 13.1,
      "passLevel": "Level SPP (認証関係者パス)",
      "pdfUrl": "",
      "desc": "Zone RED へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-USER-1789628610254",
      "code": "SPP",
      "name": "SPP 　音響",
      "floor": "1f",
      "x": 59,
      "y": 18.2,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628637412",
      "code": "TEC",
      "name": "TEC 07",
      "floor": "1f",
      "x": 54.7,
      "y": 13.6,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628655669",
      "code": "TEC",
      "name": "TEC",
      "floor": "1f",
      "x": 53.7,
      "y": 17.9,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628674294",
      "code": "TEC",
      "name": "TEC",
      "floor": "1f",
      "x": 51.3,
      "y": 13.7,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628686308",
      "code": "TEC",
      "name": "TEC",
      "floor": "1f",
      "x": 51.1,
      "y": 17.5,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628719100",
      "code": "SPT",
      "name": "SPT54　IFOFFICE",
      "floor": "1f",
      "x": 48.3,
      "y": 13.7,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789628739933",
      "code": "SPT",
      "name": "SPT54　IF OFFICE",
      "floor": "1f",
      "x": 48.1,
      "y": 17.9,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789629012630",
      "code": "TEC",
      "name": "TEC",
      "floor": "1f",
      "x": 45.7,
      "y": 14.1,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789629023280",
      "code": "TEC",
      "name": "TEC",
      "floor": "1f",
      "x": 45.1,
      "y": 17.6,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789629051506",
      "code": "FNB",
      "name": "スイムミル",
      "floor": "1f",
      "x": 33.6,
      "y": 14.3,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789629094531",
      "code": "SPT",
      "name": "メインプール入口（北）",
      "floor": "1f",
      "x": 33.9,
      "y": 19.7,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789629414107",
      "code": "SPT",
      "name": "メインプール入口（南）",
      "floor": "1f",
      "x": 34.6,
      "y": 51.3,
      "passLevel": "Level SACD (特別通行証・SACDs)",
      "pdfUrl": "",
      "desc": "",
      "isManned": true,
      "importance": "high",
      "color": "#f59e0b"
    },
    {
      "id": "ACP-USER-1789629495723",
      "code": "VEM",
      "name": "中央入口",
      "floor": "1f",
      "x": 16.3,
      "y": 49,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-SEC-1",
      "code": "SEC",
      "name": "VSCC",
      "floor": "1f",
      "x": 37.5,
      "y": 10.9,
      "passLevel": "Level SEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "Zone RED へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-SEC-3",
      "code": "SEC",
      "name": "SEC　Police Command Centre",
      "floor": "1f",
      "x": 21,
      "y": 71.7,
      "passLevel": "Level SEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "Zone RED へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-CER-1",
      "code": "SPT",
      "name": "SPT70　AthleteDining",
      "floor": "1f",
      "x": 17.1,
      "y": 71.1,
      "passLevel": "Level CER (認証関係者パス)",
      "pdfUrl": "",
      "desc": "レストランへの導線"
    },
    {
      "id": "ACP-USER-1789629962340",
      "code": "SPT",
      "name": "SPT062",
      "floor": "1f",
      "x": 63.6,
      "y": 54.6,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789630009162",
      "code": "SPT",
      "name": "ミックスゾーン出口",
      "floor": "1f",
      "x": 74.3,
      "y": 49.6,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789630033786",
      "code": "PRS",
      "name": "ミックスゾーン",
      "floor": "1f",
      "x": 85.5,
      "y": 49.1,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-SEC-2",
      "code": "SPT",
      "name": "会場外入口（南）",
      "floor": "1f",
      "x": 82.5,
      "y": 67.8,
      "passLevel": "Level SEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "外との導線"
    },
    {
      "id": "ACP-TEC-11",
      "code": "MED",
      "name": "医務室",
      "floor": "1f",
      "x": 75.5,
      "y": 65.7,
      "passLevel": "Level TEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "医務室入口"
    },
    {
      "id": "ACP-SPT-2",
      "code": "MED",
      "name": "MED　医務室入口",
      "floor": "1f",
      "x": 75.7,
      "y": 54.1,
      "passLevel": "Level SPT (認証関係者パス)",
      "pdfUrl": "",
      "desc": "医務室への入口"
    },
    {
      "id": "ACP-SPP-3",
      "code": "SPT",
      "name": "FOP入口",
      "floor": "1f",
      "x": 73.2,
      "y": 54.2,
      "passLevel": "Level 2 (選手・チーム役員エリア)",
      "pdfUrl": "",
      "desc": "FOPへの導線"
    },
    {
      "id": "ACP-USER-1789629935740",
      "code": "SPT",
      "name": "SPT　FOP入口",
      "floor": "1f",
      "x": 71,
      "y": 54.1,
      "passLevel": "Level 2 (選手・チーム役員エリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-TEC-10",
      "code": "SPT",
      "name": "SPT",
      "floor": "1f",
      "x": 68.7,
      "y": 54.1,
      "passLevel": "Level TEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "FOP入口"
    },
    {
      "id": "ACP-TEC-1",
      "code": "DOP",
      "name": "DOP",
      "floor": "1f",
      "x": 51.5,
      "y": 66.6,
      "passLevel": "Level TEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "ドーピング検査スペースの入口"
    },
    {
      "id": "ACP-TEC-7",
      "code": "SPT",
      "name": "サブプール出口",
      "floor": "1f",
      "x": 46.8,
      "y": 79.2,
      "passLevel": "Level 2 (選手・チーム役員エリア)",
      "pdfUrl": "",
      "desc": "サブプールと会場外との導線"
    },
    {
      "id": "ACP-USER-1789631762434",
      "code": "Tec",
      "name": "Tec Storage",
      "floor": "outdoor",
      "x": 40.8,
      "y": 28.5,
      "passLevel": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-SEC-9",
      "code": "SEC",
      "name": "(SEC-9）Pedestrian Screening Area",
      "floor": "outdoor",
      "x": 37.5,
      "y": 62.9,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "pdfUrl": "",
      "desc": "Zone FOH へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-TEC-4",
      "code": "TKT",
      "name": "TKT01～03　Ticketoffice",
      "floor": "outdoor",
      "x": 28,
      "y": 58.5,
      "passLevel": "Level TEC (認証関係者パス)",
      "pdfUrl": "",
      "desc": "Zone RED へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-USER-1789631949714",
      "code": "SEC",
      "name": "SEC PSA",
      "floor": "outdoor",
      "x": 38.9,
      "y": 56.3,
      "passLevel": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789631997610",
      "code": "VEM",
      "name": "TOBIO サブエントランス",
      "floor": "outdoor",
      "x": 50.9,
      "y": 25.4,
      "passLevel": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789632025329",
      "code": "SPT",
      "name": "Tobio 中央入口",
      "floor": "outdoor",
      "x": 45.3,
      "y": 52.3,
      "passLevel": "Level 2 (選手・チーム役員エリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789632055521",
      "code": "SEC",
      "name": "VAO",
      "floor": "outdoor",
      "x": 29.6,
      "y": 27.2,
      "passLevel": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789632088505",
      "code": "sec",
      "name": "PCP",
      "floor": "outdoor",
      "x": 24,
      "y": 36,
      "passLevel": "Level 6 (大会運営・スタッフエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-USER-1789632208579",
      "code": "BRS",
      "name": "BRS compound",
      "floor": "outdoor",
      "x": 74.8,
      "y": 19.4,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "pdfUrl": "",
      "desc": ""
    },
    {
      "id": "ACP-BRS-19",
      "code": "BRS",
      "name": "Broadcast Mixed Zone (BRS-19)",
      "floor": "1f",
      "x": 78.3,
      "y": 49,
      "passLevel": "Level BRS (認証関係者パス)",
      "desc": "Zone 4,5+SACDS へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-BRS-14",
      "code": "BRS",
      "name": "RHB Equipment Storage (BRS-14)",
      "floor": "outdoor",
      "x": 68,
      "y": 13.8,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "desc": "Zone 5 へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-BRS-7",
      "code": "BRS",
      "name": "HB Audio",
      "floor": "outdoor",
      "x": 69.7,
      "y": 15.4,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "Zone 5 へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-BRS-2",
      "code": "BRS",
      "name": "RHB Office",
      "floor": "outdoor",
      "x": 72.2,
      "y": 15.4,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "Zone 5 へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-BRS-3",
      "code": "BRS",
      "name": "HB Dining",
      "floor": "outdoor",
      "x": 75.3,
      "y": 18,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "Zone 5 へのアクセス管理検問ポータル。"
    },
    {
      "id": "ACP-2F-01",
      "code": "2F-01",
      "name": "北側諸室 最奥入口 (仮)",
      "floor": "2f",
      "x": 47.2,
      "y": 7.7,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "desc": "北側最奥の部屋扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-02",
      "code": "2F-02",
      "name": "北側通路 通路側扉 (仮)",
      "floor": "2f",
      "x": 47.9,
      "y": 11.4,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "desc": "北側通路・部屋扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-03",
      "code": "2F-03",
      "name": "北側中央 諸室扉 (仮)",
      "floor": "2f",
      "x": 54.9,
      "y": 11.3,
      "passLevel": "Level 5 (放送・HB/RHBエリア)",
      "desc": "北側中央部屋扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-04",
      "code": "2F-04",
      "name": "北側東寄り 諸室扉 (仮)",
      "floor": "2f",
      "x": 59.9,
      "y": 11,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "北側東寄り部屋扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-05",
      "code": "2F-05",
      "name": "北側スタンド階段・記者席入口 (仮)",
      "floor": "2f",
      "x": 61.2,
      "y": 15.6,
      "passLevel": "Level 4 (報道・プレス)",
      "desc": "北側スタンド階段・客席入口。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-06",
      "code": "2F-06",
      "name": "南側スタンド西側 階段入口 (仮)",
      "floor": "2f",
      "x": 59.6,
      "y": 54.6,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "南側スタンド西側階段。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-07",
      "code": "2F-07",
      "name": "南側スタンド東側 階段入口 (仮)",
      "floor": "2f",
      "x": 67,
      "y": 54.5,
      "passLevel": "Level 4 (フォト・撮影)",
      "desc": "南側スタンド東側階段。現場照合後に正式名称へ更新可能。"
    },
    {
      "id": "ACP-2F-08",
      "code": "2F-08",
      "name": "南側外側通路 西側扉 (仮)",
      "floor": "2f",
      "x": 59.5,
      "y": 59.8,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "南側外側通路西側扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-09",
      "code": "2F-09",
      "name": "南側外側通路 東側扉 (仮)",
      "floor": "2f",
      "x": 67.2,
      "y": 60,
      "passLevel": "Level 2 (選手・チーム役員エリア)",
      "desc": "南側外側通路東側扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-10",
      "code": "2F-10",
      "name": "西側 コンコース連絡口 (仮)",
      "floor": "2f",
      "x": 32.3,
      "y": 63.8,
      "passLevel": "Level FOH (観客・一般エリア)",
      "desc": "西側メインコンコース連絡口。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-11",
      "code": "2F-11",
      "name": "南西 通路中間扉 (仮)",
      "floor": "2f",
      "x": 27.4,
      "y": 66.9,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "南西通路中間セキュリティ扉。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-2F-12",
      "code": "2F-12",
      "name": "南西 階段・EV出口前 (仮)",
      "floor": "2f",
      "x": 26,
      "y": 67,
      "passLevel": "Level 4 (報道・プレスエリア)",
      "desc": "南西EV・階段出口正面ゲート。現場照合後に正式名称へ更新可能。",
      "pdfUrl": ""
    },
    {
      "id": "ACP-USER-0343",
      "code": "テスト",
      "name": "テスト",
      "floor": "2f",
      "x": 31,
      "y": 27,
      "passLevel": "Level 1 (競技エリア / FOP・選手・役員)",
      "pdfUrl": "",
      "desc": "",
      "isManned": true,
      "importance": "high",
      "color": "#f59e0b"
    }
  ]
};

if (typeof window !== "undefined") {
  window.VENUE_DATA = VENUE_DATA;
}

// データ永続化 (LocalStorage) & 自動保存ヘルパーコード定義
const DATA_STORAGE_HELPER_CODE = "// データ永続化 (LocalStorage) & 自動保存ヘルパー (V23)\nconst DataStorage = {\n  STORAGE_KEY: 'OFFLINE_VENUE_MAP_DATA_V24',\n\n  init() {\n    let saved = null;\n    try {\n      saved = localStorage.getItem(this.STORAGE_KEY);\n    } catch (e) {}\n\n    if (saved) {\n      try {\n        const parsed = JSON.parse(saved);\n        if (Array.isArray(parsed.rooms)) {\n          parsed.rooms.forEach(savedRoom => {\n            const existingIdx = VENUE_DATA.rooms.findIndex(r => r.id === savedRoom.id);\n            if (existingIdx !== -1) {\n              VENUE_DATA.rooms[existingIdx] = savedRoom;\n            } else {\n              VENUE_DATA.rooms.push(savedRoom);\n            }\n          });\n        }\n        if (Array.isArray(parsed.acps)) {\n          parsed.acps.forEach(savedAcp => {\n            const existingIdx = VENUE_DATA.acps.findIndex(a => a.id === savedAcp.id);\n            if (existingIdx !== -1) {\n              VENUE_DATA.acps[existingIdx] = savedAcp;\n            } else {\n              VENUE_DATA.acps.push(savedAcp);\n            }\n          });\n        }\n        this.save();\n      } catch (e) {\n        console.warn('LocalStorage parse error:', e);\n      }\n    }\n  },\n\n  save() {\n    try {\n      localStorage.setItem(this.STORAGE_KEY, JSON.stringify({\n        rooms: VENUE_DATA.rooms,\n        acps: VENUE_DATA.acps\n      }));\n    } catch (e) {\n      console.error('LocalStorage save error:', e);\n    }\n  },\n\n  reset() {\n    try {\n      for (let i = 1; i <= 30; i++) {\n        localStorage.removeItem('OFFLINE_VENUE_MAP_DATA_V' + i);\n      }\n      localStorage.removeItem('OFFLINE_VENUE_MAP_DATA');\n      localStorage.removeItem('OFFLINE_VENUE_MAP_LAST_FLOOR');\n    } catch(e) {}\n    location.reload();\n  },\n\n  generateDataJs() {\n    return '/**\\n' +\n      ' * オフライン会場マップ - データ管理モジュール (VENUE_DATA)\\n' +\n      ' * 最新編集データ (全諸室・ACP統合保存版)\\n' +\n      ' */\\n\\n' +\n      'const VENUE_DATA = ' + JSON.stringify(VENUE_DATA, null, 2) + ';\\n\\n' +\n      'if (typeof window !== \"undefined\") { window.VENUE_DATA = VENUE_DATA; }\\n\\n' +\n      DATA_STORAGE_HELPER_CODE;\n  },\n\n  exportDataJs() {\n    const jsText = this.generateDataJs();\n    const blob = new Blob([jsText], { type: 'application/javascript;charset=utf-8' });\n    const url = URL.createObjectURL(blob);\n    const a = document.createElement('a');\n    a.href = url;\n    a.download = 'data.js';\n    document.body.appendChild(a);\n    a.click();\n    setTimeout(() => {\n      document.body.removeChild(a);\n      URL.revokeObjectURL(url);\n    }, 200);\n  }\n};\n\nif (typeof window !== 'undefined') {\n  window.VENUE_DATA = VENUE_DATA;\n  window.DataStorage = DataStorage;\n}\n\nif (typeof window !== 'undefined' && typeof localStorage !== 'undefined') {\n  DataStorage.init();\n}";

// データ永続化 (LocalStorage) & 自動保存ヘルパー (V23)
const DataStorage = {
  STORAGE_KEY: 'OFFLINE_VENUE_MAP_DATA_V24',

  init() {
    let saved = null;
    try {
      saved = localStorage.getItem(this.STORAGE_KEY);
    } catch (e) {}

    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed.rooms)) {
          parsed.rooms.forEach(savedRoom => {
            const existingIdx = VENUE_DATA.rooms.findIndex(r => r.id === savedRoom.id);
            if (existingIdx !== -1) {
              VENUE_DATA.rooms[existingIdx] = savedRoom;
            } else {
              VENUE_DATA.rooms.push(savedRoom);
            }
          });
        }
        if (Array.isArray(parsed.acps)) {
          parsed.acps.forEach(savedAcp => {
            const existingIdx = VENUE_DATA.acps.findIndex(a => a.id === savedAcp.id);
            if (existingIdx !== -1) {
              VENUE_DATA.acps[existingIdx] = savedAcp;
            } else {
              VENUE_DATA.acps.push(savedAcp);
            }
          });
        }
        this.save();
      } catch (e) {
        console.warn('LocalStorage parse error:', e);
      }
    }
  },

  save() {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify({
        rooms: VENUE_DATA.rooms,
        acps: VENUE_DATA.acps
      }));
    } catch (e) {
      console.error('LocalStorage save error:', e);
    }
  },

  reset() {
    try {
      for (let i = 1; i <= 30; i++) {
        localStorage.removeItem('OFFLINE_VENUE_MAP_DATA_V' + i);
      }
      localStorage.removeItem('OFFLINE_VENUE_MAP_DATA');
      localStorage.removeItem('OFFLINE_VENUE_MAP_LAST_FLOOR');
    } catch(e) {}
    location.reload();
  },

  generateDataJs() {
    return '/**\n' +
      ' * オフライン会場マップ - データ管理モジュール (VENUE_DATA)\n' +
      ' * 最新編集データ (全諸室・ACP統合保存版)\n' +
      ' */\n\n' +
      'const VENUE_DATA = ' + JSON.stringify(VENUE_DATA, null, 2) + ';\n\n' +
      'if (typeof window !== "undefined") { window.VENUE_DATA = VENUE_DATA; }\n\n' +
      DATA_STORAGE_HELPER_CODE;
  },

  exportDataJs() {
    const jsText = this.generateDataJs();
    const blob = new Blob([jsText], { type: 'application/javascript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'data.js';
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 200);
  }
};

if (typeof window !== 'undefined') {
  window.VENUE_DATA = VENUE_DATA;
  window.DataStorage = DataStorage;
}

if (typeof window !== 'undefined' && typeof localStorage !== 'undefined') {
  DataStorage.init();
}
